image: python:3.6

pages:
  before_script:
    - python -m pip install mkdocs mkdocs-material pymdown-extensions
  script:
    - cp CHANGELOG.md docs/changelog.md
    - python -m mkdocs build -d public
  only:
    refs:
      - dev
  artifacts:
    paths:
      - public